// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/notifications/subscribe": {
    params: {};
  };
  "/api/notifications/check": {
    params: {};
  };
  "/api/weather/profile": {
    params: {};
  };
  "/sites/browse": {
    params: {};
  };
  "/auth/signin": {
    params: {};
  };
  "/sites/:slug": {
    params: {
      "slug": string;
    };
  };
  "/api/auth/*": {
    params: {
      "*": string;
    };
  };
  "/api/sites": {
    params: {};
  };
  "/api/sites/:slug": {
    params: {
      "slug": string;
    };
  };
  "/api/sites/:slug/profile": {
    params: {
      "slug": string;
    };
  };
  "/api/sites/near": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/settings": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/notifications/subscribe" | "/api/notifications/check" | "/api/weather/profile" | "/sites/browse" | "/auth/signin" | "/sites/:slug" | "/api/auth/*" | "/api/sites" | "/api/sites/:slug" | "/api/sites/:slug/profile" | "/api/sites/near" | "/dashboard" | "/settings";
  };
  "routes/api.notifications.subscribe.tsx": {
    id: "routes/api.notifications.subscribe";
    page: "/api/notifications/subscribe";
  };
  "routes/api.notifications.check.tsx": {
    id: "routes/api.notifications.check";
    page: "/api/notifications/check";
  };
  "routes/api.weather.profile.tsx": {
    id: "routes/api.weather.profile";
    page: "/api/weather/profile";
  };
  "routes/sites.browse.tsx": {
    id: "routes/sites.browse";
    page: "/sites/browse";
  };
  "routes/auth.signin.tsx": {
    id: "routes/auth.signin";
    page: "/auth/signin";
  };
  "routes/sites.$slug.tsx": {
    id: "routes/sites.$slug";
    page: "/sites/:slug";
  };
  "routes/api.auth.$.tsx": {
    id: "routes/api.auth.$";
    page: "/api/auth/*";
  };
  "routes/api.sites.tsx": {
    id: "routes/api.sites";
    page: "/api/sites" | "/api/sites/:slug" | "/api/sites/:slug/profile" | "/api/sites/near";
  };
  "routes/api.sites.$slug.tsx": {
    id: "routes/api.sites.$slug";
    page: "/api/sites/:slug" | "/api/sites/:slug/profile";
  };
  "routes/api.sites.$slug.profile.tsx": {
    id: "routes/api.sites.$slug.profile";
    page: "/api/sites/:slug/profile";
  };
  "routes/api.sites.near.tsx": {
    id: "routes/api.sites.near";
    page: "/api/sites/near";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/_auth.tsx": {
    id: "routes/_auth";
    page: "/dashboard" | "/settings";
  };
  "routes/_auth.dashboard.tsx": {
    id: "routes/_auth.dashboard";
    page: "/dashboard";
  };
  "routes/_auth.settings.tsx": {
    id: "routes/_auth.settings";
    page: "/settings";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/api.notifications.subscribe": typeof import("./app/routes/api.notifications.subscribe.tsx");
  "routes/api.notifications.check": typeof import("./app/routes/api.notifications.check.tsx");
  "routes/api.weather.profile": typeof import("./app/routes/api.weather.profile.tsx");
  "routes/sites.browse": typeof import("./app/routes/sites.browse.tsx");
  "routes/auth.signin": typeof import("./app/routes/auth.signin.tsx");
  "routes/sites.$slug": typeof import("./app/routes/sites.$slug.tsx");
  "routes/api.auth.$": typeof import("./app/routes/api.auth.$.tsx");
  "routes/api.sites": typeof import("./app/routes/api.sites.tsx");
  "routes/api.sites.$slug": typeof import("./app/routes/api.sites.$slug.tsx");
  "routes/api.sites.$slug.profile": typeof import("./app/routes/api.sites.$slug.profile.tsx");
  "routes/api.sites.near": typeof import("./app/routes/api.sites.near.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/_auth": typeof import("./app/routes/_auth.tsx");
  "routes/_auth.dashboard": typeof import("./app/routes/_auth.dashboard.tsx");
  "routes/_auth.settings": typeof import("./app/routes/_auth.settings.tsx");
};